/* Lerninhalte der App, nach Themen gruppiert.
 *
 * Jedes Thema hat eine Liste von Lernkarten. Eine Karte besteht aus:
 *   front: Vorderseite (Frage bzw. Begriff)
 *   back:  Rückseite  (gesuchte Antwort)
 *   icon:  Emoji, das gross auf der Karte angezeigt wird
 *
 * Alle Modi (Karteikarten, Quiz, Tippen, Liste, Falsche üben) arbeiten mit
 * diesem einheitlichen Format, egal welches Thema gewählt ist.
 */

const TOPICS = [
  {
    id: "eu",
    name: "EU-Länder",
    emoji: "🇪🇺",
    subtitle: "Die 27 EU-Staaten und ihre Hauptstädte",
    promptLabel: "Land",
    answerLabel: "Hauptstadt",
    // Bei der Quiz-/Tippen-Frage vorangestellter Text. Leer = nur die Frage zeigen.
    quizPrompt: "Wie heißt die Hauptstadt von",
    typePlaceholder: "Hauptstadt eingeben…",
    cards: [
      { front: "Belgien",      back: "Brüssel",     icon: "🇧🇪" },
      { front: "Bulgarien",    back: "Sofia",       icon: "🇧🇬" },
      { front: "Dänemark",     back: "Kopenhagen",  icon: "🇩🇰" },
      { front: "Deutschland",  back: "Berlin",      icon: "🇩🇪" },
      { front: "Estland",      back: "Tallinn",     icon: "🇪🇪" },
      { front: "Finnland",     back: "Helsinki",    icon: "🇫🇮" },
      { front: "Frankreich",   back: "Paris",       icon: "🇫🇷" },
      { front: "Griechenland", back: "Athen",       icon: "🇬🇷" },
      { front: "Irland",       back: "Dublin",      icon: "🇮🇪" },
      { front: "Italien",      back: "Rom",         icon: "🇮🇹" },
      { front: "Kroatien",     back: "Zagreb",      icon: "🇭🇷" },
      { front: "Lettland",     back: "Riga",        icon: "🇱🇻" },
      { front: "Litauen",      back: "Vilnius",     icon: "🇱🇹" },
      { front: "Luxemburg",    back: "Luxemburg",   icon: "🇱🇺" },
      { front: "Malta",        back: "Valletta",    icon: "🇲🇹" },
      { front: "Niederlande",  back: "Amsterdam",   icon: "🇳🇱" },
      { front: "Österreich",   back: "Wien",        icon: "🇦🇹" },
      { front: "Polen",        back: "Warschau",    icon: "🇵🇱" },
      { front: "Portugal",     back: "Lissabon",    icon: "🇵🇹" },
      { front: "Rumänien",     back: "Bukarest",    icon: "🇷🇴" },
      { front: "Schweden",     back: "Stockholm",   icon: "🇸🇪" },
      { front: "Slowakei",     back: "Bratislava",  icon: "🇸🇰" },
      { front: "Slowenien",    back: "Ljubljana",   icon: "🇸🇮" },
      { front: "Spanien",      back: "Madrid",      icon: "🇪🇸" },
      { front: "Tschechien",   back: "Prag",        icon: "🇨🇿" },
      { front: "Ungarn",       back: "Budapest",    icon: "🇭🇺" },
      { front: "Zypern",       back: "Nikosia",     icon: "🇨🇾" },
    ],
  },

  {
    id: "blueten",
    name: "Blütenpflanzen",
    emoji: "🌼",
    subtitle: "Aufbau, Bestäubung, Früchte & Samenverbreitung",
    promptLabel: "Frage",
    answerLabel: "Antwort",
    quizPrompt: "",
    typePlaceholder: "Antwort eingeben…",
    cards: [
      // --- Aufbau und Funktion der Blütenpflanze ---
      { front: "Welche vier Grundorgane besitzt jede Blütenpflanze?", back: "Wurzel, Stängel, Blätter und Blüte", icon: "🌱" },
      { front: "Welches Organ verankert die Pflanze im Boden und nimmt Wasser auf?", back: "Die Wurzel", icon: "🌱" },
      { front: "Wie heißt der oberirdische Teil der Pflanze (Stängel, Blätter, Blüten)?", back: "Der Spross", icon: "🌱" },
      { front: "Welche Aufgabe hat der Stängel (die Sprossachse)?", back: "Er stützt die Pflanze und trägt Blätter und Blüten", icon: "🌿" },
      { front: "Wie nennt man den verholzten Stängel eines Baumes?", back: "Stamm", icon: "🌳" },
      { front: "In welchem Pflanzenteil bildet die Pflanze Traubenzucker?", back: "In den Blättern", icon: "🍃" },
      { front: "Was braucht die Pflanze, um in den Blättern Zucker aufzubauen?", back: "Wasser, Kohlenstoffdioxid und Sonnenlicht", icon: "☀️" },
      { front: "Wie heißt der Vorgang, bei dem Pflanzen mit Sonnenlicht Nährstoffe aufbauen?", back: "Fotosynthese", icon: "☀️" },
      { front: "Welches Gas geben Pflanzen bei der Fotosynthese ab?", back: "Sauerstoff", icon: "💨" },
      { front: "Wie heißen die Leitröhren, die Wasser in der Pflanze transportieren?", back: "Gefäße", icon: "💧" },
      { front: "Wie heißen die kleinen Öffnungen in den Blättern, über die Wasserdampf abgegeben wird?", back: "Spaltöffnungen", icon: "🍃" },
      { front: "Womit öffnen und schließen sich die Spaltöffnungen?", back: "Mit Schließzellen", icon: "🍃" },
      { front: "Welche Hauptaufgabe hat die Blüte?", back: "Die Fortpflanzung", icon: "🌸" },

      // --- Bau und Funktion der Blüte ---
      { front: "Wie heißen die äußeren grünen Blätter der Blüte, die die Knospe schützen?", back: "Kelchblätter", icon: "🌸" },
      { front: "Wie heißen die meist großen, farbigen Blätter, die Bestäuber anlocken?", back: "Kronblätter", icon: "🌷" },
      { front: "Wie nennt man Kelch- und Kronblätter zusammen?", back: "Blütenhülle", icon: "🌸" },
      { front: "Wie heißen die männlichen Fortpflanzungsorgane der Blüte?", back: "Staubblätter", icon: "🌼" },
      { front: "Aus welchen zwei Teilen besteht ein Staubblatt?", back: "Staubfaden und Staubbeutel", icon: "🌼" },
      { front: "Wo entsteht der Blütenstaub (Pollen)?", back: "In den Staubbeuteln", icon: "🌼" },
      { front: "Wie heißen die männlichen Fortpflanzungszellen?", back: "Pollenkörner", icon: "🌼" },
      { front: "Wie heißt das weibliche Fortpflanzungsorgan der Blüte?", back: "Der Stempel", icon: "🌸" },
      { front: "Aus welchen drei Teilen besteht der Stempel?", back: "Narbe, Griffel und Fruchtknoten", icon: "🌸" },
      { front: "In welchem Teil des Stempels liegt die Samenanlage mit der Eizelle?", back: "Im Fruchtknoten", icon: "🌸" },
      { front: "Wie heißt die weibliche Fortpflanzungszelle?", back: "Die Eizelle", icon: "🥚" },
      { front: "Wie heißt der klebrige obere Teil des Stempels, auf dem der Pollen landet?", back: "Die Narbe", icon: "🌸" },

      // --- Bestäubung und Befruchtung ---
      { front: "Wie nennt man die Übertragung von Pollen auf die Narbe?", back: "Bestäubung", icon: "🐝" },
      { front: "Wodurch werden Blüten bestäubt?", back: "Durch Insekten oder durch den Wind", icon: "🐝" },
      { front: "Wie heißen Pflanzen, die von Insekten bestäubt werden?", back: "Insektenblütler", icon: "🐝" },
      { front: "Wie heißen Pflanzen, die vom Wind bestäubt werden?", back: "Windblütler", icon: "💨" },
      { front: "Womit locken Insektenblütler ihre Bestäuber an?", back: "Mit Farbe, Duft und Nektar", icon: "🌺" },
      { front: "Wie sind die Blüten der Windblütler gebaut?", back: "Klein und unscheinbar", icon: "💨" },
      { front: "Wie heißen die männlichen Blüten der Hasel?", back: "Kätzchen", icon: "🌳" },
      { front: "Was wächst aus dem Pollenkorn, sobald es auf der Narbe liegt?", back: "Der Pollenschlauch", icon: "🌸" },
      { front: "Wohin wächst der Pollenschlauch?", back: "Durch den Griffel bis zur Samenanlage im Fruchtknoten", icon: "🌸" },
      { front: "Wie nennt man die Verschmelzung von männlicher Geschlechtszelle und Eizelle?", back: "Befruchtung", icon: "💞" },
      { front: "Wo findet die Befruchtung statt?", back: "Im Fruchtknoten", icon: "🌸" },

      // --- Von der Blüte zur Frucht ---
      { front: "Woraus entsteht nach der Befruchtung die Frucht?", back: "Aus dem Fruchtknoten", icon: "🍒" },
      { front: "Woraus entsteht der Samen?", back: "Aus der Samenanlage", icon: "🌰" },
      { front: "Wie heißt eine Frucht mit einem harten Stein im Inneren (z. B. Kirsche)?", back: "Steinfrucht", icon: "🍒" },
      { front: "Wie heißt eine fleischige Frucht mit vielen Samen (z. B. Tomate, Traube)?", back: "Beere", icon: "🍇" },
      { front: "Wie heißt die Frucht, bei der viele kleine Früchtchen zusammenwachsen (z. B. Brombeere)?", back: "Sammelfrucht", icon: "🫐" },
      { front: "Aus welchem Blütenteil wächst beim Apfel das Fruchtfleisch?", back: "Aus dem Blütenboden", icon: "🍎" },
      { front: "Wie heißt die trockene Frucht von Bohne und Erbse?", back: "Hülsenfrucht", icon: "🫛" },
      { front: "Ist die Tomate biologisch eine Frucht oder Gemüse?", back: "Eine Frucht", icon: "🍅" },

      // --- Verbreitung von Samen und Früchten ---
      { front: "Auf welche vier Arten können Samen und Früchte verbreitet werden?", back: "Durch Wind, Wasser, Tiere und Selbstverbreitung", icon: "🍃" },
      { front: "Wodurch wird der Löwenzahn verbreitet?", back: "Durch den Wind", icon: "🌬️" },
      { front: "Wie heißen Früchte mit Widerhaken, die im Fell von Tieren hängen bleiben?", back: "Klettfrüchte", icon: "🦔" },
      { front: "Wie verbreiten sich Ginster und Springkraut?", back: "Durch Selbstverbreitung", icon: "💥" },
      { front: "Wodurch wird die Kokosnuss verbreitet?", back: "Durch Wasser", icon: "🥥" },
      { front: "Warum sind viele Früchte auffällig gefärbt?", back: "Damit Tiere sie fressen und die Samen verbreiten", icon: "🐦" },

      // --- Samen und Keimung ---
      { front: "Was braucht ein Samen zum Keimen?", back: "Wasser, Luft und Wärme", icon: "🌱" },
      { front: "Was braucht eine Pflanze zusätzlich zum Wachsen?", back: "Sonnenlicht und Mineralstoffe", icon: "☀️" },
      { front: "Aus welchen drei Teilen besteht der Keimling?", back: "Keimwurzel, Keimstängel und Keimblätter", icon: "🌱" },
      { front: "Was befindet sich im Inneren eines Samens?", back: "Ein Embryo", icon: "🌰" },
      { front: "Wie nennt man die Vermehrung ohne Samen (z. B. durch Zwiebeln oder Ausläufer)?", back: "Ungeschlechtliche Vermehrung", icon: "🧅" },
      { front: "Welches Speicherorgan lässt die Tulpe früh im Frühling austreiben?", back: "Die Zwiebel", icon: "🧅" },
    ],
  },

  {
    id: "verbs",
    name: "Englische Verben",
    emoji: "🇬🇧",
    subtitle: "Unregelmäßige Verben – Gegenwart & Vergangenheit",
    promptLabel: "Deutsch",
    answerLabel: "Englisch (Gegenwart – Vergangenheit)",
    quizPrompt: "",
    typePlaceholder: "englisch eingeben…",
    // Karten mit present/past: im Modus "Tippen" werden zwei Felder
    // (Gegenwart und Vergangenheit) abgefragt. "back" wird beim Laden
    // automatisch aus present/past gebildet ("be – was/were").
    cards: [
      { front: "sein",                 present: "be",         past: "was/were",        icon: "🇬🇧" },
      { front: "schlagen / besiegen",  present: "beat",       past: "beat",            icon: "🇬🇧" },
      { front: "bekommen",             present: "get",        past: "got",             icon: "🇬🇧" },
      { front: "beginnen",             present: "begin",      past: "began",           icon: "🇬🇧" },
      { front: "beißen",               present: "bite",       past: "bit",             icon: "🇬🇧" },
      { front: "blasen",               present: "blow",       past: "blew",            icon: "🇬🇧" },
      { front: "brechen",              present: "break",      past: "broke",           icon: "🇬🇧" },
      { front: "bringen",              present: "bring",      past: "brought",         icon: "🇬🇧" },
      { front: "bauen",                present: "build",      past: "built",           icon: "🇬🇧" },
      { front: "brennen",              present: "burn",       past: "burnt/burned",    icon: "🇬🇧" },
      { front: "bersten",              present: "burst",      past: "burst",           icon: "🇬🇧" },
      { front: "können",               present: "can",        past: "could",           icon: "🇬🇧" },
      { front: "fangen",               present: "catch",      past: "caught",          icon: "🇬🇧" },
      { front: "wählen",               present: "choose",     past: "chose",           icon: "🇬🇧" },
      { front: "kommen",               present: "come",       past: "came",            icon: "🇬🇧" },
      { front: "schneiden",            present: "cut",        past: "cut",             icon: "🇬🇧" },
      { front: "kosten",               present: "cost",       past: "cost",            icon: "🇬🇧" },
      { front: "machen / tun",         present: "do",         past: "did",             icon: "🇬🇧" },
      { front: "zeichnen",             present: "draw",       past: "drew",            icon: "🇬🇧" },
      { front: "träumen",              present: "dream",      past: "dreamt/dreamed",  icon: "🇬🇧" },
      { front: "trinken",              present: "drink",      past: "drank",           icon: "🇬🇧" },
      { front: "verhandeln / handhaben", present: "deal",     past: "dealt",           icon: "🇬🇧" },
      { front: "fahren",               present: "drive",      past: "drove",           icon: "🇬🇧" },
      { front: "essen",                present: "eat",        past: "ate",             icon: "🇬🇧" },
      { front: "fallen",               present: "fall",       past: "fell",            icon: "🇬🇧" },
      { front: "kämpfen",              present: "fight",      past: "fought",          icon: "🇬🇧" },
      { front: "finden",               present: "find",       past: "found",           icon: "🇬🇧" },
      { front: "fliegen",              present: "fly",        past: "flew",            icon: "🇬🇧" },
      { front: "vergessen",            present: "forget",     past: "forgot",          icon: "🇬🇧" },
      { front: "vergeben",             present: "forgive",    past: "forgave",         icon: "🇬🇧" },
      { front: "frieren",              present: "freeze",     past: "froze",           icon: "🇬🇧" },
      { front: "geben",                present: "give",       past: "gave",            icon: "🇬🇧" },
      { front: "wachsen",              present: "grow",       past: "grew",            icon: "🇬🇧" },
      { front: "hängen",               present: "hang",       past: "hung",            icon: "🇬🇧" },
      { front: "haben",                present: "have",       past: "had",             icon: "🇬🇧" },
      { front: "hören",                present: "hear",       past: "heard",           icon: "🇬🇧" },
      { front: "verstecken (sich)",    present: "hide",       past: "hid",             icon: "🇬🇧" },
      { front: "schlagen / treffen",   present: "hit",        past: "hit",             icon: "🇬🇧" },
      { front: "halten",               present: "hold",       past: "held",            icon: "🇬🇧" },
      { front: "verletzen",            present: "hurt",       past: "hurt",            icon: "🇬🇧" },
      { front: "behalten",             present: "keep",       past: "kept",            icon: "🇬🇧" },
      { front: "knien",                present: "kneel",      past: "knelt/kneeled",   icon: "🇬🇧" },
      { front: "wissen",               present: "know",       past: "knew",            icon: "🇬🇧" },
      { front: "legen / hinlegen",     present: "lay",        past: "laid",            icon: "🇬🇧" },
      { front: "gehen",                present: "go",         past: "went",            icon: "🇬🇧" },
      { front: "führen",               present: "lead",       past: "led",             icon: "🇬🇧" },
      { front: "lernen",               present: "learn",      past: "learnt/learned",  icon: "🇬🇧" },
      { front: "verlassen",            present: "leave",      past: "left",            icon: "🇬🇧" },
      { front: "leihen",               present: "lend",       past: "lent",            icon: "🇬🇧" },
      { front: "lassen",               present: "let",        past: "let",             icon: "🇬🇧" },
      { front: "liegen / sich hinlegen", present: "lie",      past: "lay",             icon: "🇬🇧" },
      { front: "leuchten",             present: "light",      past: "lit/lighted",     icon: "🇬🇧" },
      { front: "verlieren",            present: "lose",       past: "lost",            icon: "🇬🇧" },
      { front: "machen / erstellen",   present: "make",       past: "made",            icon: "🇬🇧" },
      { front: "meinen",               present: "mean",       past: "meant",           icon: "🇬🇧" },
      { front: "treffen",              present: "meet",       past: "met",             icon: "🇬🇧" },
      { front: "müssen",               present: "must",       past: "had to",          icon: "🇬🇧" },
      { front: "bezahlen",             present: "pay",        past: "paid",            icon: "🇬🇧" },
      { front: "biegen",               present: "bend",       past: "bent",            icon: "🇬🇧" },
      { front: "wetten",               present: "bet",        past: "bet",             icon: "🇬🇧" },
      { front: "werden",               present: "become",     past: "became",          icon: "🇬🇧" },
      { front: "stellen",              present: "put",        past: "put",             icon: "🇬🇧" },
      { front: "lesen",                present: "read",       past: "read",            icon: "🇬🇧" },
      { front: "reiten",               present: "ride",       past: "rode",            icon: "🇬🇧" },
      { front: "aufsteigen",           present: "rise",       past: "rose",            icon: "🇬🇧" },
      { front: "rennen",               present: "run",        past: "ran",             icon: "🇬🇧" },
      { front: "sagen",                present: "say",        past: "said",            icon: "🇬🇧" },
      { front: "sehen",                present: "see",        past: "saw",             icon: "🇬🇧" },
      { front: "verkaufen",            present: "sell",       past: "sold",            icon: "🇬🇧" },
      { front: "senden",               present: "send",       past: "sent",            icon: "🇬🇧" },
      { front: "setzen",               present: "set",        past: "set",             icon: "🇬🇧" },
      { front: "schütteln",            present: "shake",      past: "shook",           icon: "🇬🇧" },
      { front: "schrumpfen",           present: "shrink",     past: "shrank",          icon: "🇬🇧" },
      { front: "schießen",             present: "shoot",      past: "shot",            icon: "🇬🇧" },
      { front: "singen",               present: "sing",       past: "sang",            icon: "🇬🇧" },
      { front: "sinken",               present: "sink",       past: "sank",            icon: "🇬🇧" },
      { front: "scheinen",             present: "shine",      past: "shone",           icon: "🇬🇧" },
      { front: "sitzen",               present: "sit",        past: "sat",             icon: "🇬🇧" },
      { front: "schlafen",             present: "sleep",      past: "slept",           icon: "🇬🇧" },
      { front: "rutschen",             present: "slide",      past: "slid",            icon: "🇬🇧" },
      { front: "riechen",              present: "smell",      past: "smelt/smelled",   icon: "🇬🇧" },
      { front: "sprechen",             present: "speak",      past: "spoke",           icon: "🇬🇧" },
      { front: "buchstabieren",        present: "spell",      past: "spelt/spelled",   icon: "🇬🇧" },
      { front: "spenden",              present: "spend",      past: "spent",           icon: "🇬🇧" },
      { front: "verschütten",          present: "spill",      past: "spilt/spilled",   icon: "🇬🇧" },
      { front: "teilen / spalten",     present: "split",      past: "split",           icon: "🇬🇧" },
      { front: "verderben",            present: "spoil",      past: "spoilt/spoiled",  icon: "🇬🇧" },
      { front: "verbreiten",           present: "spread",     past: "spread",          icon: "🇬🇧" },
      { front: "stehen",               present: "stand",      past: "stood",           icon: "🇬🇧" },
      { front: "stecken",              present: "stick",      past: "stuck",           icon: "🇬🇧" },
      { front: "schwören",             present: "swear",      past: "swore",           icon: "🇬🇧" },
      { front: "schwimmen",            present: "swim",       past: "swam",            icon: "🇬🇧" },
      { front: "nehmen",               present: "take",       past: "took",            icon: "🇬🇧" },
      { front: "lehren",               present: "teach",      past: "taught",          icon: "🇬🇧" },
      { front: "reißen",               present: "tear",       past: "tore",            icon: "🇬🇧" },
      { front: "sagen / erzählen",     present: "tell",       past: "told",            icon: "🇬🇧" },
      { front: "denken",               present: "think",      past: "thought",         icon: "🇬🇧" },
      { front: "werfen",               present: "throw",      past: "threw",           icon: "🇬🇧" },
      { front: "verstehen",            present: "understand", past: "understood",      icon: "🇬🇧" },
      { front: "wecken",               present: "wake",       past: "woke",            icon: "🇬🇧" },
      { front: "tragen / anziehen",    present: "wear",       past: "wore",            icon: "🇬🇧" },
      { front: "gewinnen",             present: "win",        past: "won",             icon: "🇬🇧" },
      { front: "schreiben",            present: "write",      past: "wrote",           icon: "🇬🇧" },
    ],
  },

  {
    id: "french",
    name: "Französische Verben",
    emoji: "🇫🇷",
    subtitle: "Présent (alle Personen) & Passé composé",
    promptLabel: "Deutsch",
    answerLabel: "Französisch",
    quizPrompt: "",
    typePlaceholder: "französisch eingeben…",
    // Konjugationskarten: present ist ein Objekt (je/tu/il/nous/vous/ils),
    // pc = Passé composé (1. Person). Im Modus "Tippen" werden alle Formen
    // einzeln abgefragt. "back" wird beim Laden kompakt zusammengesetzt.
    cards: [
      { front: "sprechen", fr: "parler",
        present: { je: "je parle", tu: "tu parles", il: "il parle", nous: "nous parlons", vous: "vous parlez", ils: "ils parlent" },
        pc: "j'ai parlé", icon: "🇫🇷" },
      { front: "schliessen", fr: "fermer",
        present: { je: "je ferme", tu: "tu fermes", il: "il ferme", nous: "nous fermons", vous: "vous fermez", ils: "ils ferment" },
        pc: "j'ai fermé", icon: "🇫🇷" },
      { front: "essen", fr: "manger",
        present: { je: "je mange", tu: "tu manges", il: "il mange", nous: "nous mangeons", vous: "vous mangez", ils: "ils mangent" },
        pc: "j'ai mangé", icon: "🇫🇷" },
      { front: "nehmen", fr: "prendre",
        present: { je: "je prends", tu: "tu prends", il: "il prend", nous: "nous prenons", vous: "vous prenez", ils: "ils prennent" },
        pc: "j'ai pris", icon: "🇫🇷" },
      { front: "schreiben", fr: "écrire",
        present: { je: "j'écris", tu: "tu écris", il: "il écrit", nous: "nous écrivons", vous: "vous écrivez", ils: "ils écrivent" },
        pc: "j'ai écrit", icon: "🇫🇷" },
      { front: "haben", fr: "avoir",
        present: { je: "j'ai", tu: "tu as", il: "il a", nous: "nous avons", vous: "vous avez", ils: "ils ont" },
        pc: "j'ai eu", icon: "🇫🇷" },
      { front: "sein", fr: "être",
        present: { je: "je suis", tu: "tu es", il: "il est", nous: "nous sommes", vous: "vous êtes", ils: "ils sont" },
        pc: "j'ai été", icon: "🇫🇷" },
      { front: "machen", fr: "faire",
        present: { je: "je fais", tu: "tu fais", il: "il fait", nous: "nous faisons", vous: "vous faites", ils: "ils font" },
        pc: "j'ai fait", icon: "🇫🇷" },
      { front: "wollen", fr: "vouloir",
        present: { je: "je veux", tu: "tu veux", il: "il veut", nous: "nous voulons", vous: "vous voulez", ils: "ils veulent" },
        pc: "j'ai voulu", icon: "🇫🇷" },
      { front: "lesen", fr: "lire",
        present: { je: "je lis", tu: "tu lis", il: "il lit", nous: "nous lisons", vous: "vous lisez", ils: "ils lisent" },
        pc: "j'ai lu", icon: "🇫🇷" },
      { front: "abreisen / weggehen", fr: "partir",
        present: { je: "je pars", tu: "tu pars", il: "il part", nous: "nous partons", vous: "vous partez", ils: "ils partent" },
        pc: "je suis parti(e)", icon: "🇫🇷" },
      { front: "runtersteigen", fr: "descendre",
        present: { je: "je descends", tu: "tu descends", il: "il descend", nous: "nous descendons", vous: "vous descendez", ils: "ils descendent" },
        pc: "je suis descendu(e)", icon: "🇫🇷" },
      { front: "fallen", fr: "tomber",
        present: { je: "je tombe", tu: "tu tombes", il: "il tombe", nous: "nous tombons", vous: "vous tombez", ils: "ils tombent" },
        pc: "je suis tombé(e)", icon: "🇫🇷" },
      { front: "denken", fr: "penser",
        present: { je: "je pense", tu: "tu penses", il: "il pense", nous: "nous pensons", vous: "vous pensez", ils: "ils pensent" },
        pc: "j'ai pensé", icon: "🇫🇷" },
      { front: "stellen / setzen", fr: "mettre",
        present: { je: "je mets", tu: "tu mets", il: "il met", nous: "nous mettons", vous: "vous mettez", ils: "ils mettent" },
        pc: "j'ai mis", icon: "🇫🇷" },
      { front: "eintreten", fr: "entrer",
        present: { je: "j'entre", tu: "tu entres", il: "il entre", nous: "nous entrons", vous: "vous entrez", ils: "ils entrent" },
        pc: "je suis entré(e)", icon: "🇫🇷" },
      { front: "schauen", fr: "regarder",
        present: { je: "je regarde", tu: "tu regardes", il: "il regarde", nous: "nous regardons", vous: "vous regardez", ils: "ils regardent" },
        pc: "j'ai regardé", icon: "🇫🇷" },
      { front: "können", fr: "pouvoir",
        present: { je: "je peux", tu: "tu peux", il: "il peut", nous: "nous pouvons", vous: "vous pouvez", ils: "ils peuvent" },
        pc: "j'ai pu", icon: "🇫🇷" },
      { front: "hinausgehen", fr: "sortir",
        present: { je: "je sors", tu: "tu sors", il: "il sort", nous: "nous sortons", vous: "vous sortez", ils: "ils sortent" },
        pc: "je suis sorti(e)", icon: "🇫🇷" },
      { front: "verstehen", fr: "comprendre",
        present: { je: "je comprends", tu: "tu comprends", il: "il comprend", nous: "nous comprenons", vous: "vous comprenez", ils: "ils comprennent" },
        pc: "j'ai compris", icon: "🇫🇷" },
      { front: "gehen", fr: "aller",
        present: { je: "je vais", tu: "tu vas", il: "il va", nous: "nous allons", vous: "vous allez", ils: "ils vont" },
        pc: "je suis allé(e)", icon: "🇫🇷" },
      { front: "müssen", fr: "devoir",
        present: { je: "je dois", tu: "tu dois", il: "il doit", nous: "nous devons", vous: "vous devez", ils: "ils doivent" },
        pc: "j'ai dû", icon: "🇫🇷" },
      { front: "kommen", fr: "venir",
        present: { je: "je viens", tu: "tu viens", il: "il vient", nous: "nous venons", vous: "vous venez", ils: "ils viennent" },
        pc: "je suis venu(e)", icon: "🇫🇷" },
      { front: "lernen", fr: "apprendre",
        present: { je: "j'apprends", tu: "tu apprends", il: "il apprend", nous: "nous apprenons", vous: "vous apprenez", ils: "ils apprennent" },
        pc: "j'ai appris", icon: "🇫🇷" },
      { front: "wohnen", fr: "habiter",
        present: { je: "j'habite", tu: "tu habites", il: "il habite", nous: "nous habitons", vous: "vous habitez", ils: "ils habitent" },
        pc: "j'ai habité", icon: "🇫🇷" },
      { front: "telefonieren", fr: "téléphoner",
        present: { je: "je téléphone", tu: "tu téléphones", il: "il téléphone", nous: "nous téléphonons", vous: "vous téléphonez", ils: "ils téléphonent" },
        pc: "j'ai téléphoné", icon: "🇫🇷" },
      { front: "bleiben", fr: "rester",
        present: { je: "je reste", tu: "tu restes", il: "il reste", nous: "nous restons", vous: "vous restez", ils: "ils restent" },
        pc: "je suis resté(e)", icon: "🇫🇷" },
      { front: "beenden", fr: "finir",
        present: { je: "je finis", tu: "tu finis", il: "il finit", nous: "nous finissons", vous: "vous finissez", ils: "ils finissent" },
        pc: "j'ai fini", icon: "🇫🇷" },
      { front: "wählen", fr: "choisir",
        present: { je: "je choisis", tu: "tu choisis", il: "il choisit", nous: "nous choisissons", vous: "vous choisissez", ils: "ils choisissent" },
        pc: "j'ai choisi", icon: "🇫🇷" },
      { front: "schlafen", fr: "dormir",
        present: { je: "je dors", tu: "tu dors", il: "il dort", nous: "nous dormons", vous: "vous dormez", ils: "ils dorment" },
        pc: "j'ai dormi", icon: "🇫🇷" },
      { front: "verkaufen", fr: "vendre",
        present: { je: "je vends", tu: "tu vends", il: "il vend", nous: "nous vendons", vous: "vous vendez", ils: "ils vendent" },
        pc: "j'ai vendu", icon: "🇫🇷" },
      { front: "warten", fr: "attendre",
        present: { je: "j'attends", tu: "tu attends", il: "il attend", nous: "nous attendons", vous: "vous attendez", ils: "ils attendent" },
        pc: "j'ai attendu", icon: "🇫🇷" },
      { front: "antworten", fr: "répondre",
        present: { je: "je réponds", tu: "tu réponds", il: "il répond", nous: "nous répondons", vous: "vous répondez", ils: "ils répondent" },
        pc: "j'ai répondu", icon: "🇫🇷" },
      { front: "verlieren", fr: "perdre",
        present: { je: "je perds", tu: "tu perds", il: "il perd", nous: "nous perdons", vous: "vous perdez", ils: "ils perdent" },
        pc: "j'ai perdu", icon: "🇫🇷" },
      { front: "sehen", fr: "voir",
        present: { je: "je vois", tu: "tu vois", il: "il voit", nous: "nous voyons", vous: "vous voyez", ils: "ils voient" },
        pc: "j'ai vu", icon: "🇫🇷" },
      { front: "wissen", fr: "savoir",
        present: { je: "je sais", tu: "tu sais", il: "il sait", nous: "nous savons", vous: "vous savez", ils: "ils savent" },
        pc: "j'ai su", icon: "🇫🇷" },
      { front: "trinken", fr: "boire",
        present: { je: "je bois", tu: "tu bois", il: "il boit", nous: "nous buvons", vous: "vous buvez", ils: "ils boivent" },
        pc: "j'ai bu", icon: "🇫🇷" },
      { front: "bekommen", fr: "recevoir",
        present: { je: "je reçois", tu: "tu reçois", il: "il reçoit", nous: "nous recevons", vous: "vous recevez", ils: "ils reçoivent" },
        pc: "j'ai reçu", icon: "🇫🇷" },
      { front: "kennen", fr: "connaître",
        present: { je: "je connais", tu: "tu connais", il: "il connaît", nous: "nous connaissons", vous: "vous connaissez", ils: "ils connaissent" },
        pc: "j'ai connu", icon: "🇫🇷" },
      { front: "leben", fr: "vivre",
        present: { je: "je vis", tu: "tu vis", il: "il vit", nous: "nous vivons", vous: "vous vivez", ils: "ils vivent" },
        pc: "j'ai vécu", icon: "🇫🇷" },
      { front: "öffnen", fr: "ouvrir",
        present: { je: "j'ouvre", tu: "tu ouvres", il: "il ouvre", nous: "nous ouvrons", vous: "vous ouvrez", ils: "ils ouvrent" },
        pc: "j'ai ouvert", icon: "🇫🇷" },
      { front: "schenken / anbieten / offerieren", fr: "offrir",
        present: { je: "j'offre", tu: "tu offres", il: "il offre", nous: "nous offrons", vous: "vous offrez", ils: "ils offrent" },
        pc: "j'ai offert", icon: "🇫🇷" },
      { front: "sagen", fr: "dire",
        present: { je: "je dis", tu: "tu dis", il: "il dit", nous: "nous disons", vous: "vous dites", ils: "ils disent" },
        pc: "j'ai dit", icon: "🇫🇷" },
      { front: "spielen", fr: "jouer",
        present: { je: "je joue", tu: "tu joues", il: "il joue", nous: "nous jouons", vous: "vous jouez", ils: "ils jouent" },
        pc: "j'ai joué", icon: "🇫🇷" },
      { front: "bezahlen", fr: "payer",
        present: { je: "je paie", tu: "tu paies", il: "il paie", nous: "nous payons", vous: "vous payez", ils: "ils paient" },
        pc: "j'ai payé", icon: "🇫🇷" },
      { front: "rennen", fr: "courir",
        present: { je: "je cours", tu: "tu cours", il: "il court", nous: "nous courons", vous: "vous courez", ils: "ils courent" },
        pc: "j'ai couru", icon: "🇫🇷" },
      { front: "ankommen", fr: "arriver",
        present: { je: "j'arrive", tu: "tu arrives", il: "il arrive", nous: "nous arrivons", vous: "vous arrivez", ils: "ils arrivent" },
        pc: "je suis arrivé(e)", icon: "🇫🇷" },
      { front: "geboren werden", fr: "naître",
        present: { je: "je nais", tu: "tu nais", il: "il naît", nous: "nous naissons", vous: "vous naissez", ils: "ils naissent" },
        pc: "je suis né(e)", icon: "🇫🇷" },
      { front: "sterben", fr: "mourir",
        present: { je: "je meurs", tu: "tu meurs", il: "il meurt", nous: "nous mourons", vous: "vous mourez", ils: "ils meurent" },
        pc: "je suis mort(e)", icon: "🇫🇷" },
      { front: "hinaufsteigen", fr: "monter",
        present: { je: "je monte", tu: "tu montes", il: "il monte", nous: "nous montons", vous: "vous montez", ils: "ils montent" },
        pc: "je suis monté(e)", icon: "🇫🇷" },
      { front: "heimkommen", fr: "rentrer",
        present: { je: "je rentre", tu: "tu rentres", il: "il rentre", nous: "nous rentrons", vous: "vous rentrez", ils: "ils rentrent" },
        pc: "je suis rentré(e)", icon: "🇫🇷" },
      { front: "zurückkehren", fr: "retourner",
        present: { je: "je retourne", tu: "tu retournes", il: "il retourne", nous: "nous retournons", vous: "vous retournez", ils: "ils retournent" },
        pc: "je suis retourné(e)", icon: "🇫🇷" },
      { front: "werden", fr: "devenir",
        present: { je: "je deviens", tu: "tu deviens", il: "il devient", nous: "nous devenons", vous: "vous devenez", ils: "ils deviennent" },
        pc: "je suis devenu(e)", icon: "🇫🇷" },
    ],
  },
];


