/* Lerninhalte der App, nach Themen gruppiert.
 *
 * Jedes Thema hat eine Liste von Lernkarten. Eine Karte besteht aus:
 *   front: Vorderseite (Frage bzw. Begriff)
 *   back:  Rückseite  (gesuchte Antwort)
 *   icon:  Emoji, das gross auf der Karte angezeigt wird
 *
 * Alle Modi (Karteikarten, Quiz, Tippen, Liste, Falsche üben) arbeiten mit
 * diesem einheitlichen Format, egal welches Thema gewählt ist.
 */

const TOPICS = [
  {
    id: "eu",
    name: "EU-Länder",
    emoji: "🇪🇺",
    subtitle: "Die 27 EU-Staaten und ihre Hauptstädte",
    promptLabel: "Land",
    answerLabel: "Hauptstadt",
    // Bei der Quiz-/Tippen-Frage vorangestellter Text. Leer = nur die Frage zeigen.
    quizPrompt: "Wie heißt die Hauptstadt von",
    typePlaceholder: "Hauptstadt eingeben…",
    cards: [
      { front: "Belgien",      back: "Brüssel",     icon: "🇧🇪" },
      { front: "Bulgarien",    back: "Sofia",       icon: "🇧🇬" },
      { front: "Dänemark",     back: "Kopenhagen",  icon: "🇩🇰" },
      { front: "Deutschland",  back: "Berlin",      icon: "🇩🇪" },
      { front: "Estland",      back: "Tallinn",     icon: "🇪🇪" },
      { front: "Finnland",     back: "Helsinki",    icon: "🇫🇮" },
      { front: "Frankreich",   back: "Paris",       icon: "🇫🇷" },
      { front: "Griechenland", back: "Athen",       icon: "🇬🇷" },
      { front: "Irland",       back: "Dublin",      icon: "🇮🇪" },
      { front: "Italien",      back: "Rom",         icon: "🇮🇹" },
      { front: "Kroatien",     back: "Zagreb",      icon: "🇭🇷" },
      { front: "Lettland",     back: "Riga",        icon: "🇱🇻" },
      { front: "Litauen",      back: "Vilnius",     icon: "🇱🇹" },
      { front: "Luxemburg",    back: "Luxemburg",   icon: "🇱🇺" },
      { front: "Malta",        back: "Valletta",    icon: "🇲🇹" },
      { front: "Niederlande",  back: "Amsterdam",   icon: "🇳🇱" },
      { front: "Österreich",   back: "Wien",        icon: "🇦🇹" },
      { front: "Polen",        back: "Warschau",    icon: "🇵🇱" },
      { front: "Portugal",     back: "Lissabon",    icon: "🇵🇹" },
      { front: "Rumänien",     back: "Bukarest",    icon: "🇷🇴" },
      { front: "Schweden",     back: "Stockholm",   icon: "🇸🇪" },
      { front: "Slowakei",     back: "Bratislava",  icon: "🇸🇰" },
      { front: "Slowenien",    back: "Ljubljana",   icon: "🇸🇮" },
      { front: "Spanien",      back: "Madrid",      icon: "🇪🇸" },
      { front: "Tschechien",   back: "Prag",        icon: "🇨🇿" },
      { front: "Ungarn",       back: "Budapest",    icon: "🇭🇺" },
      { front: "Zypern",       back: "Nikosia",     icon: "🇨🇾" },
    ],
  },

  {
    id: "blueten",
    name: "Blütenpflanzen",
    emoji: "🌼",
    subtitle: "Aufbau, Bestäubung, Früchte & Samenverbreitung",
    promptLabel: "Frage",
    answerLabel: "Antwort",
    quizPrompt: "",
    typePlaceholder: "Antwort eingeben…",
    cards: [
      // --- Aufbau und Funktion der Blütenpflanze ---
      { front: "Welche vier Grundorgane besitzt jede Blütenpflanze?", back: "Wurzel, Stängel, Blätter und Blüte", icon: "🌱" },
      { front: "Welches Organ verankert die Pflanze im Boden und nimmt Wasser auf?", back: "Die Wurzel", icon: "🌱" },
      { front: "Wie heißt der oberirdische Teil der Pflanze (Stängel, Blätter, Blüten)?", back: "Der Spross", icon: "🌱" },
      { front: "Welche Aufgabe hat der Stängel (die Sprossachse)?", back: "Er stützt die Pflanze und trägt Blätter und Blüten", icon: "🌿" },
      { front: "Wie nennt man den verholzten Stängel eines Baumes?", back: "Stamm", icon: "🌳" },
      { front: "In welchem Pflanzenteil bildet die Pflanze Traubenzucker?", back: "In den Blättern", icon: "🍃" },
      { front: "Was braucht die Pflanze, um in den Blättern Zucker aufzubauen?", back: "Wasser, Kohlenstoffdioxid und Sonnenlicht", icon: "☀️" },
      { front: "Wie heißt der Vorgang, bei dem Pflanzen mit Sonnenlicht Nährstoffe aufbauen?", back: "Fotosynthese", icon: "☀️" },
      { front: "Welches Gas geben Pflanzen bei der Fotosynthese ab?", back: "Sauerstoff", icon: "💨" },
      { front: "Wie heißen die Leitröhren, die Wasser in der Pflanze transportieren?", back: "Gefäße", icon: "💧" },
      { front: "Wie heißen die kleinen Öffnungen in den Blättern, über die Wasserdampf abgegeben wird?", back: "Spaltöffnungen", icon: "🍃" },
      { front: "Womit öffnen und schließen sich die Spaltöffnungen?", back: "Mit Schließzellen", icon: "🍃" },
      { front: "Welche Hauptaufgabe hat die Blüte?", back: "Die Fortpflanzung", icon: "🌸" },

      // --- Bau und Funktion der Blüte ---
      { front: "Wie heißen die äußeren grünen Blätter der Blüte, die die Knospe schützen?", back: "Kelchblätter", icon: "🌸" },
      { front: "Wie heißen die meist großen, farbigen Blätter, die Bestäuber anlocken?", back: "Kronblätter", icon: "🌷" },
      { front: "Wie nennt man Kelch- und Kronblätter zusammen?", back: "Blütenhülle", icon: "🌸" },
      { front: "Wie heißen die männlichen Fortpflanzungsorgane der Blüte?", back: "Staubblätter", icon: "🌼" },
      { front: "Aus welchen zwei Teilen besteht ein Staubblatt?", back: "Staubfaden und Staubbeutel", icon: "🌼" },
      { front: "Wo entsteht der Blütenstaub (Pollen)?", back: "In den Staubbeuteln", icon: "🌼" },
      { front: "Wie heißen die männlichen Fortpflanzungszellen?", back: "Pollenkörner", icon: "🌼" },
      { front: "Wie heißt das weibliche Fortpflanzungsorgan der Blüte?", back: "Der Stempel", icon: "🌸" },
      { front: "Aus welchen drei Teilen besteht der Stempel?", back: "Narbe, Griffel und Fruchtknoten", icon: "🌸" },
      { front: "In welchem Teil des Stempels liegt die Samenanlage mit der Eizelle?", back: "Im Fruchtknoten", icon: "🌸" },
      { front: "Wie heißt die weibliche Fortpflanzungszelle?", back: "Die Eizelle", icon: "🥚" },
      { front: "Wie heißt der klebrige obere Teil des Stempels, auf dem der Pollen landet?", back: "Die Narbe", icon: "🌸" },

      // --- Bestäubung und Befruchtung ---
      { front: "Wie nennt man die Übertragung von Pollen auf die Narbe?", back: "Bestäubung", icon: "🐝" },
      { front: "Wodurch werden Blüten bestäubt?", back: "Durch Insekten oder durch den Wind", icon: "🐝" },
      { front: "Wie heißen Pflanzen, die von Insekten bestäubt werden?", back: "Insektenblütler", icon: "🐝" },
      { front: "Wie heißen Pflanzen, die vom Wind bestäubt werden?", back: "Windblütler", icon: "💨" },
      { front: "Womit locken Insektenblütler ihre Bestäuber an?", back: "Mit Farbe, Duft und Nektar", icon: "🌺" },
      { front: "Wie sind die Blüten der Windblütler gebaut?", back: "Klein und unscheinbar", icon: "💨" },
      { front: "Wie heißen die männlichen Blüten der Hasel?", back: "Kätzchen", icon: "🌳" },
      { front: "Was wächst aus dem Pollenkorn, sobald es auf der Narbe liegt?", back: "Der Pollenschlauch", icon: "🌸" },
      { front: "Wohin wächst der Pollenschlauch?", back: "Durch den Griffel bis zur Samenanlage im Fruchtknoten", icon: "🌸" },
      { front: "Wie nennt man die Verschmelzung von männlicher Geschlechtszelle und Eizelle?", back: "Befruchtung", icon: "💞" },
      { front: "Wo findet die Befruchtung statt?", back: "Im Fruchtknoten", icon: "🌸" },

      // --- Von der Blüte zur Frucht ---
      { front: "Woraus entsteht nach der Befruchtung die Frucht?", back: "Aus dem Fruchtknoten", icon: "🍒" },
      { front: "Woraus entsteht der Samen?", back: "Aus der Samenanlage", icon: "🌰" },
      { front: "Wie heißt eine Frucht mit einem harten Stein im Inneren (z. B. Kirsche)?", back: "Steinfrucht", icon: "🍒" },
      { front: "Wie heißt eine fleischige Frucht mit vielen Samen (z. B. Tomate, Traube)?", back: "Beere", icon: "🍇" },
      { front: "Wie heißt die Frucht, bei der viele kleine Früchtchen zusammenwachsen (z. B. Brombeere)?", back: "Sammelfrucht", icon: "🫐" },
      { front: "Aus welchem Blütenteil wächst beim Apfel das Fruchtfleisch?", back: "Aus dem Blütenboden", icon: "🍎" },
      { front: "Wie heißt die trockene Frucht von Bohne und Erbse?", back: "Hülsenfrucht", icon: "🫛" },
      { front: "Ist die Tomate biologisch eine Frucht oder Gemüse?", back: "Eine Frucht", icon: "🍅" },

      // --- Verbreitung von Samen und Früchten ---
      { front: "Auf welche vier Arten können Samen und Früchte verbreitet werden?", back: "Durch Wind, Wasser, Tiere und Selbstverbreitung", icon: "🍃" },
      { front: "Wodurch wird der Löwenzahn verbreitet?", back: "Durch den Wind", icon: "🌬️" },
      { front: "Wie heißen Früchte mit Widerhaken, die im Fell von Tieren hängen bleiben?", back: "Klettfrüchte", icon: "🦔" },
      { front: "Wie verbreiten sich Ginster und Springkraut?", back: "Durch Selbstverbreitung", icon: "💥" },
      { front: "Wodurch wird die Kokosnuss verbreitet?", back: "Durch Wasser", icon: "🥥" },
      { front: "Warum sind viele Früchte auffällig gefärbt?", back: "Damit Tiere sie fressen und die Samen verbreiten", icon: "🐦" },

      // --- Samen und Keimung ---
      { front: "Was braucht ein Samen zum Keimen?", back: "Wasser, Luft und Wärme", icon: "🌱" },
      { front: "Was braucht eine Pflanze zusätzlich zum Wachsen?", back: "Sonnenlicht und Mineralstoffe", icon: "☀️" },
      { front: "Aus welchen drei Teilen besteht der Keimling?", back: "Keimwurzel, Keimstängel und Keimblätter", icon: "🌱" },
      { front: "Was befindet sich im Inneren eines Samens?", back: "Ein Embryo", icon: "🌰" },
      { front: "Wie nennt man die Vermehrung ohne Samen (z. B. durch Zwiebeln oder Ausläufer)?", back: "Ungeschlechtliche Vermehrung", icon: "🧅" },
      { front: "Welches Speicherorgan lässt die Tulpe früh im Frühling austreiben?", back: "Die Zwiebel", icon: "🧅" },
    ],
  },

  {
    id: "verbs",
    name: "Englische Verben",
    emoji: "🇬🇧",
    subtitle: "Unregelmäßige Verben – Gegenwart & Vergangenheit",
    promptLabel: "Deutsch",
    answerLabel: "Englisch (Gegenwart – Vergangenheit)",
    quizPrompt: "",
    typePlaceholder: "englisch eingeben…",
    // Karten mit present/past: im Modus "Tippen" werden zwei Felder
    // (Gegenwart und Vergangenheit) abgefragt. "back" wird beim Laden
    // automatisch aus present/past gebildet ("be – was/were").
    cards: [
      { front: "sein",                 present: "be",         past: "was/were",        icon: "🇬🇧" },
      { front: "schlagen / besiegen",  present: "beat",       past: "beat",            icon: "🇬🇧" },
      { front: "bekommen",             present: "get",        past: "got",             icon: "🇬🇧" },
      { front: "beginnen",             present: "begin",      past: "began",           icon: "🇬🇧" },
      { front: "beißen",               present: "bite",       past: "bit",             icon: "🇬🇧" },
      { front: "blasen",               present: "blow",       past: "blew",            icon: "🇬🇧" },
      { front: "brechen",              present: "break",      past: "broke",           icon: "🇬🇧" },
      { front: "bringen",              present: "bring",      past: "brought",         icon: "🇬🇧" },
      { front: "bauen",                present: "build",      past: "built",           icon: "🇬🇧" },
      { front: "brennen",              present: "burn",       past: "burnt/burned",    icon: "🇬🇧" },
      { front: "bersten",              present: "burst",      past: "burst",           icon: "🇬🇧" },
      { front: "können",               present: "can",        past: "could",           icon: "🇬🇧" },
      { front: "fangen",               present: "catch",      past: "caught",          icon: "🇬🇧" },
      { front: "wählen",               present: "choose",     past: "chose",           icon: "🇬🇧" },
      { front: "kommen",               present: "come",       past: "came",            icon: "🇬🇧" },
      { front: "schneiden",            present: "cut",        past: "cut",             icon: "🇬🇧" },
      { front: "kosten",               present: "cost",       past: "cost",            icon: "🇬🇧" },
      { front: "machen / tun",         present: "do",         past: "did",             icon: "🇬🇧" },
      { front: "zeichnen",             present: "draw",       past: "drew",            icon: "🇬🇧" },
      { front: "träumen",              present: "dream",      past: "dreamt/dreamed",  icon: "🇬🇧" },
      { front: "trinken",              present: "drink",      past: "drank",           icon: "🇬🇧" },
      { front: "verhandeln / handhaben", present: "deal",     past: "dealt",           icon: "🇬🇧" },
      { front: "fahren",               present: "drive",      past: "drove",           icon: "🇬🇧" },
      { front: "essen",                present: "eat",        past: "ate",             icon: "🇬🇧" },
      { front: "fallen",               present: "fall",       past: "fell",            icon: "🇬🇧" },
      { front: "kämpfen",              present: "fight",      past: "fought",          icon: "🇬🇧" },
      { front: "finden",               present: "find",       past: "found",           icon: "🇬🇧" },
      { front: "fliegen",              present: "fly",        past: "flew",            icon: "🇬🇧" },
      { front: "vergessen",            present: "forget",     past: "forgot",          icon: "🇬🇧" },
      { front: "vergeben",             present: "forgive",    past: "forgave",         icon: "🇬🇧" },
      { front: "frieren",              present: "freeze",     past: "froze",           icon: "🇬🇧" },
      { front: "geben",                present: "give",       past: "gave",            icon: "🇬🇧" },
      { front: "wachsen",              present: "grow",       past: "grew",            icon: "🇬🇧" },
      { front: "hängen",               present: "hang",       past: "hung",            icon: "🇬🇧" },
      { front: "haben",                present: "have",       past: "had",             icon: "🇬🇧" },
      { front: "hören",                present: "hear",       past: "heard",           icon: "🇬🇧" },
      { front: "verstecken (sich)",    present: "hide",       past: "hid",             icon: "🇬🇧" },
      { front: "schlagen / treffen",   present: "hit",        past: "hit",             icon: "🇬🇧" },
      { front: "halten",               present: "hold",       past: "held",            icon: "🇬🇧" },
      { front: "verletzen",            present: "hurt",       past: "hurt",            icon: "🇬🇧" },
      { front: "behalten",             present: "keep",       past: "kept",            icon: "🇬🇧" },
      { front: "knien",                present: "kneel",      past: "knelt/kneeled",   icon: "🇬🇧" },
      { front: "wissen",               present: "know",       past: "knew",            icon: "🇬🇧" },
      { front: "legen / hinlegen",     present: "lay",        past: "laid",            icon: "🇬🇧" },
      { front: "gehen",                present: "go",         past: "went",            icon: "🇬🇧" },
      { front: "führen",               present: "lead",       past: "led",             icon: "🇬🇧" },
      { front: "lernen",               present: "learn",      past: "learnt/learned",  icon: "🇬🇧" },
      { front: "verlassen",            present: "leave",      past: "left",            icon: "🇬🇧" },
      { front: "leihen",               present: "lend",       past: "lent",            icon: "🇬🇧" },
      { front: "lassen",               present: "let",        past: "let",             icon: "🇬🇧" },
      { front: "liegen / sich hinlegen", present: "lie",      past: "lay",             icon: "🇬🇧" },
      { front: "leuchten",             present: "light",      past: "lit/lighted",     icon: "🇬🇧" },
      { front: "verlieren",            present: "lose",       past: "lost",            icon: "🇬🇧" },
      { front: "machen / erstellen",   present: "make",       past: "made",            icon: "🇬🇧" },
      { front: "meinen",               present: "mean",       past: "meant",           icon: "🇬🇧" },
      { front: "treffen",              present: "meet",       past: "met",             icon: "🇬🇧" },
      { front: "müssen",               present: "must",       past: "had to",          icon: "🇬🇧" },
      { front: "bezahlen",             present: "pay",        past: "paid",            icon: "🇬🇧" },
      { front: "biegen",               present: "bend",       past: "bent",            icon: "🇬🇧" },
      { front: "wetten",               present: "bet",        past: "bet",             icon: "🇬🇧" },
      { front: "werden",               present: "become",     past: "became",          icon: "🇬🇧" },
      { front: "stellen",              present: "put",        past: "put",             icon: "🇬🇧" },
      { front: "lesen",                present: "read",       past: "read",            icon: "🇬🇧" },
      { front: "reiten",               present: "ride",       past: "rode",            icon: "🇬🇧" },
      { front: "aufsteigen",           present: "rise",       past: "rose",            icon: "🇬🇧" },
      { front: "rennen",               present: "run",        past: "ran",             icon: "🇬🇧" },
      { front: "sagen",                present: "say",        past: "said",            icon: "🇬🇧" },
      { front: "sehen",                present: "see",        past: "saw",             icon: "🇬🇧" },
      { front: "verkaufen",            present: "sell",       past: "sold",            icon: "🇬🇧" },
      { front: "senden",               present: "send",       past: "sent",            icon: "🇬🇧" },
      { front: "setzen",               present: "set",        past: "set",             icon: "🇬🇧" },
      { front: "schütteln",            present: "shake",      past: "shook",           icon: "🇬🇧" },
      { front: "schrumpfen",           present: "shrink",     past: "shrank",          icon: "🇬🇧" },
      { front: "schießen",             present: "shoot",      past: "shot",            icon: "🇬🇧" },
      { front: "singen",               present: "sing",       past: "sang",            icon: "🇬🇧" },
      { front: "sinken",               present: "sink",       past: "sank",            icon: "🇬🇧" },
      { front: "scheinen",             present: "shine",      past: "shone",           icon: "🇬🇧" },
      { front: "sitzen",               present: "sit",        past: "sat",             icon: "🇬🇧" },
      { front: "schlafen",             present: "sleep",      past: "slept",           icon: "🇬🇧" },
      { front: "rutschen",             present: "slide",      past: "slid",            icon: "🇬🇧" },
      { front: "riechen",              present: "smell",      past: "smelt/smelled",   icon: "🇬🇧" },
      { front: "sprechen",             present: "speak",      past: "spoke",           icon: "🇬🇧" },
      { front: "buchstabieren",        present: "spell",      past: "spelt/spelled",   icon: "🇬🇧" },
      { front: "spenden",              present: "spend",      past: "spent",           icon: "🇬🇧" },
      { front: "verschütten",          present: "spill",      past: "spilt/spilled",   icon: "🇬🇧" },
      { front: "teilen / spalten",     present: "split",      past: "split",           icon: "🇬🇧" },
      { front: "verderben",            present: "spoil",      past: "spoilt/spoiled",  icon: "🇬🇧" },
      { front: "verbreiten",           present: "spread",     past: "spread",          icon: "🇬🇧" },
      { front: "stehen",               present: "stand",      past: "stood",           icon: "🇬🇧" },
      { front: "stecken",              present: "stick",      past: "stuck",           icon: "🇬🇧" },
      { front: "schwören",             present: "swear",      past: "swore",           icon: "🇬🇧" },
      { front: "schwimmen",            present: "swim",       past: "swam",            icon: "🇬🇧" },
      { front: "nehmen",               present: "take",       past: "took",            icon: "🇬🇧" },
      { front: "lehren",               present: "teach",      past: "taught",          icon: "🇬🇧" },
      { front: "reißen",               present: "tear",       past: "tore",            icon: "🇬🇧" },
      { front: "sagen / erzählen",     present: "tell",       past: "told",            icon: "🇬🇧" },
      { front: "denken",               present: "think",      past: "thought",         icon: "🇬🇧" },
      { front: "werfen",               present: "throw",      past: "threw",           icon: "🇬🇧" },
      { front: "verstehen",            present: "understand", past: "understood",      icon: "🇬🇧" },
      { front: "wecken",               present: "wake",       past: "woke",            icon: "🇬🇧" },
      { front: "tragen / anziehen",    present: "wear",       past: "wore",            icon: "🇬🇧" },
      { front: "gewinnen",             present: "win",        past: "won",             icon: "🇬🇧" },
      { front: "schreiben",            present: "write",      past: "wrote",           icon: "🇬🇧" },
    ],
  },
];

