// Die 27 Mitgliedsstaaten der Europäischen Union mit ihren Hauptstädten.
// Stand: 2026. Flaggen als Emoji (Regional Indicator Symbols).
const COUNTRIES = [
  { country: "Belgien",        capital: "Brüssel",     flag: "🇧🇪" },
  { country: "Bulgarien",      capital: "Sofia",       flag: "🇧🇬" },
  { country: "Dänemark",       capital: "Kopenhagen",  flag: "🇩🇰" },
  { country: "Deutschland",    capital: "Berlin",      flag: "🇩🇪" },
  { country: "Estland",        capital: "Tallinn",     flag: "🇪🇪" },
  { country: "Finnland",       capital: "Helsinki",    flag: "🇫🇮" },
  { country: "Frankreich",     capital: "Paris",       flag: "🇫🇷" },
  { country: "Griechenland",   capital: "Athen",       flag: "🇬🇷" },
  { country: "Irland",         capital: "Dublin",      flag: "🇮🇪" },
  { country: "Italien",        capital: "Rom",         flag: "🇮🇹" },
  { country: "Kroatien",       capital: "Zagreb",      flag: "🇭🇷" },
  { country: "Lettland",       capital: "Riga",        flag: "🇱🇻" },
  { country: "Litauen",        capital: "Vilnius",     flag: "🇱🇹" },
  { country: "Luxemburg",      capital: "Luxemburg",   flag: "🇱🇺" },
  { country: "Malta",          capital: "Valletta",    flag: "🇲🇹" },
  { country: "Niederlande",    capital: "Amsterdam",   flag: "🇳🇱" },
  { country: "Österreich",     capital: "Wien",        flag: "🇦🇹" },
  { country: "Polen",          capital: "Warschau",    flag: "🇵🇱" },
  { country: "Portugal",       capital: "Lissabon",    flag: "🇵🇹" },
  { country: "Rumänien",       capital: "Bukarest",    flag: "🇷🇴" },
  { country: "Schweden",       capital: "Stockholm",   flag: "🇸🇪" },
  { country: "Slowakei",       capital: "Bratislava",  flag: "🇸🇰" },
  { country: "Slowenien",      capital: "Ljubljana",   flag: "🇸🇮" },
  { country: "Spanien",        capital: "Madrid",      flag: "🇪🇸" },
  { country: "Tschechien",     capital: "Prag",        flag: "🇨🇿" },
  { country: "Ungarn",         capital: "Budapest",    flag: "🇭🇺" },
  { country: "Zypern",         capital: "Nikosia",     flag: "🇨🇾" },
];
